# Generated by Django 5.2.3 on 2025-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='django.core.mail.backends.console.EmailBackend', help_text="The email backend to use. E.g., 'django.core.mail.backends.smtp.EmailBackend'.", max_length=255)),
                ('host', models.CharField(blank=True, help_text='The email server host.', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='The port for the email server.')),
                ('use_tls', models.BooleanField(default=True, help_text='Whether to use a TLS secure connection.')),
                ('host_user', models.CharField(blank=True, help_text='Username for the email server.', max_length=255)),
                ('host_password', models.CharField(blank=True, help_text='Password for the email server.', max_length=255)),
                ('default_from_email', models.EmailField(blank=True, help_text="Default 'from' address for emails.", max_length=254)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='FileStorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_storage_backend', models.CharField(blank=True, help_text="Default file storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255)),
                ('static_storage_backend', models.CharField(blank=True, help_text="Static files storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=255)),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=255)),
                ('aws_storage_bucket_name', models.CharField(blank=True, max_length=255)),
                ('aws_s3_region_name', models.CharField(blank=True, help_text="e.g. 'us-east-1'", max_length=255)),
                ('aws_s3_custom_domain', models.CharField(blank=True, help_text="e.g. 'cdn.example.com'", max_length=255)),
            ],
            options={
                'verbose_name': 'File Storage Settings',
                'verbose_name_plural': 'File Storage Settings',
            },
        ),
    ]
