# Generated by Django 5.2.3 on 2025-06-13 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tag_updated_at_category_meta_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10)),
                ('theme_en', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10, null=True)),
                ('theme_de', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10, null=True)),
                ('theme_fr', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10, null=True)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=20)),
                ('density_en', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=20, null=True)),
                ('density_de', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=20, null=True)),
                ('density_fr', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=20, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Preference',
                'verbose_name_plural': 'Admin Preferences',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('method', models.CharField(max_length=10)),
                ('method_en', models.CharField(max_length=10, null=True)),
                ('method_de', models.CharField(max_length=10, null=True)),
                ('method_fr', models.CharField(max_length=10, null=True)),
                ('path', models.CharField(max_length=2048)),
                ('path_en', models.CharField(max_length=2048, null=True)),
                ('path_de', models.CharField(max_length=2048, null=True)),
                ('path_fr', models.CharField(max_length=2048, null=True)),
                ('status_code', models.PositiveIntegerField()),
                ('response_time_ms', models.PositiveIntegerField(help_text='Response time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
