# Generated by Django 5.2.3 on 2025-06-16 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('name_de', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_de', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_fr', models.SlugField(max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('content', models.TextField(blank=True, verbose_name='Product Markdown Content')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Product Markdown Content')),
                ('content_de', models.TextField(blank=True, null=True, verbose_name='Product Markdown Content')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='Product Markdown Content')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_de', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_de', models.SlugField(max_length=200, null=True, unique=True)),
                ('slug_fr', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('first_name_en', models.CharField(max_length=50, null=True)),
                ('first_name_de', models.CharField(max_length=50, null=True)),
                ('first_name_fr', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('last_name_en', models.CharField(max_length=50, null=True)),
                ('last_name_de', models.CharField(max_length=50, null=True)),
                ('last_name_fr', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_en', models.EmailField(max_length=254, null=True)),
                ('email_de', models.EmailField(max_length=254, null=True)),
                ('email_fr', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=250)),
                ('address_en', models.CharField(max_length=250, null=True)),
                ('address_de', models.CharField(max_length=250, null=True)),
                ('address_fr', models.CharField(max_length=250, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('postal_code_en', models.CharField(max_length=20, null=True)),
                ('postal_code_de', models.CharField(max_length=20, null=True)),
                ('postal_code_fr', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=100)),
                ('city_en', models.CharField(max_length=100, null=True)),
                ('city_de', models.CharField(max_length=100, null=True)),
                ('city_fr', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('status_en', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20, null=True)),
                ('status_de', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20, null=True)),
                ('status_fr', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory'),
        ),
    ]
