# Generated by Django 5.2.3 on 2025-06-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug_de',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug_fr',
        ),
    ]
