# Generated by Django 5.2.3 on 2025-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Awesome Site', help_text='The name of the site, used in the title tag.', max_length=255)),
                ('name_en', models.CharField(default='My Awesome Site', help_text='The name of the site, used in the title tag.', max_length=255, null=True)),
                ('name_de', models.CharField(default='My Awesome Site', help_text='The name of the site, used in the title tag.', max_length=255, null=True)),
                ('name_fr', models.CharField(default='My Awesome Site', help_text='The name of the site, used in the title tag.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the site for SEO purposes.')),
                ('description_en', models.TextField(blank=True, help_text='A short description of the site for SEO purposes.', null=True)),
                ('description_de', models.TextField(blank=True, help_text='A short description of the site for SEO purposes.', null=True)),
                ('description_fr', models.TextField(blank=True, help_text='A short description of the site for SEO purposes.', null=True)),
                ('logo', models.ImageField(blank=True, help_text='The main logo of the site.', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text="The site's favicon.", null=True, upload_to='site/')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255)),
                ('keywords_en', models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255, null=True)),
                ('keywords_de', models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255, null=True)),
                ('keywords_fr', models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Identity & SEO',
                'verbose_name_plural': 'Site Identity & SEO',
            },
        ),
    ]
