# Generated by Django 5.2.3 on 2025-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='backend_de',
            field=models.CharField(default='django.core.mail.backends.console.EmailBackend', help_text="The email backend to use. E.g., 'django.core.mail.backends.smtp.EmailBackend'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='backend_en',
            field=models.CharField(default='django.core.mail.backends.console.EmailBackend', help_text="The email backend to use. E.g., 'django.core.mail.backends.smtp.EmailBackend'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='backend_fr',
            field=models.CharField(default='django.core.mail.backends.console.EmailBackend', help_text="The email backend to use. E.g., 'django.core.mail.backends.smtp.EmailBackend'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='default_from_email_de',
            field=models.EmailField(blank=True, help_text="Default 'from' address for emails.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='default_from_email_en',
            field=models.EmailField(blank=True, help_text="Default 'from' address for emails.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='default_from_email_fr',
            field=models.EmailField(blank=True, help_text="Default 'from' address for emails.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_de',
            field=models.CharField(blank=True, help_text='The email server host.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_en',
            field=models.CharField(blank=True, help_text='The email server host.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_fr',
            field=models.CharField(blank=True, help_text='The email server host.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_password_de',
            field=models.CharField(blank=True, help_text='Password for the email server.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_password_en',
            field=models.CharField(blank=True, help_text='Password for the email server.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_password_fr',
            field=models.CharField(blank=True, help_text='Password for the email server.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_user_de',
            field=models.CharField(blank=True, help_text='Username for the email server.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_user_en',
            field=models.CharField(blank=True, help_text='Username for the email server.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='host_user_fr',
            field=models.CharField(blank=True, help_text='Username for the email server.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_access_key_id_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_access_key_id_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_access_key_id_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_s3_custom_domain_de',
            field=models.CharField(blank=True, help_text="e.g. 'cdn.example.com'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_s3_custom_domain_en',
            field=models.CharField(blank=True, help_text="e.g. 'cdn.example.com'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_s3_custom_domain_fr',
            field=models.CharField(blank=True, help_text="e.g. 'cdn.example.com'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_s3_region_name_de',
            field=models.CharField(blank=True, help_text="e.g. 'us-east-1'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_s3_region_name_en',
            field=models.CharField(blank=True, help_text="e.g. 'us-east-1'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_s3_region_name_fr',
            field=models.CharField(blank=True, help_text="e.g. 'us-east-1'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_secret_access_key_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_secret_access_key_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_secret_access_key_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_storage_bucket_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_storage_bucket_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='aws_storage_bucket_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='default_storage_backend_de',
            field=models.CharField(blank=True, help_text="Default file storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='default_storage_backend_en',
            field=models.CharField(blank=True, help_text="Default file storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='default_storage_backend_fr',
            field=models.CharField(blank=True, help_text="Default file storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='static_storage_backend_de',
            field=models.CharField(blank=True, help_text="Static files storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='static_storage_backend_en',
            field=models.CharField(blank=True, help_text="Static files storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filestoragesettings',
            name='static_storage_backend_fr',
            field=models.CharField(blank=True, help_text="Static files storage backend. E.g., 'storages.backends.s3boto3.S3Boto3Storage'.", max_length=255, null=True),
        ),
    ]
