# Generated by Django 5.2.3 on 2025-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_de',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_de',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_en',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_fr',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_de',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_de',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
