# Generated by Django 5.2.3 on 2025-06-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
