# Generated by Django 5.2.3 on 2025-06-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidentity',
            name='author',
            field=models.CharField(blank=True, help_text="The name of the site's author or organization.", max_length=100),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='author_de',
            field=models.CharField(blank=True, help_text="The name of the site's author or organization.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='author_en',
            field=models.CharField(blank=True, help_text="The name of the site's author or organization.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='author_fr',
            field=models.CharField(blank=True, help_text="The name of the site's author or organization.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email address.', max_length=254),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='contact_email_de',
            field=models.EmailField(blank=True, help_text='Public contact email address.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='contact_email_en',
            field=models.EmailField(blank=True, help_text='Public contact email address.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='contact_email_fr',
            field=models.EmailField(blank=True, help_text='Public contact email address.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL to Facebook page.'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='facebook_url_de',
            field=models.URLField(blank=True, help_text='URL to Facebook page.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='facebook_url_en',
            field=models.URLField(blank=True, help_text='URL to Facebook page.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='facebook_url_fr',
            field=models.URLField(blank=True, help_text='URL to Facebook page.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to GitHub profile.'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='github_url_de',
            field=models.URLField(blank=True, help_text='URL to GitHub profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='github_url_en',
            field=models.URLField(blank=True, help_text='URL to GitHub profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='github_url_fr',
            field=models.URLField(blank=True, help_text='URL to GitHub profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL to Instagram profile.'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='instagram_url_de',
            field=models.URLField(blank=True, help_text='URL to Instagram profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='instagram_url_en',
            field=models.URLField(blank=True, help_text='URL to Instagram profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='instagram_url_fr',
            field=models.URLField(blank=True, help_text='URL to Instagram profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL to LinkedIn profile.'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='linkedin_url_de',
            field=models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='linkedin_url_en',
            field=models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='linkedin_url_fr',
            field=models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='An alternative logo for dark backgrounds.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Public contact phone number.', max_length=20),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='phone_number_de',
            field=models.CharField(blank=True, help_text='Public contact phone number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='phone_number_en',
            field=models.CharField(blank=True, help_text='Public contact phone number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='phone_number_fr',
            field=models.CharField(blank=True, help_text='Public contact phone number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='slogan',
            field=models.CharField(blank=True, help_text='A catchy slogan or tagline for the site.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='slogan_de',
            field=models.CharField(blank=True, help_text='A catchy slogan or tagline for the site.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='slogan_en',
            field=models.CharField(blank=True, help_text='A catchy slogan or tagline for the site.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='slogan_fr',
            field=models.CharField(blank=True, help_text='A catchy slogan or tagline for the site.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='URL to Twitter profile.'),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='twitter_url_de',
            field=models.URLField(blank=True, help_text='URL to Twitter profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='twitter_url_en',
            field=models.URLField(blank=True, help_text='URL to Twitter profile.', null=True),
        ),
        migrations.AddField(
            model_name='siteidentity',
            name='twitter_url_fr',
            field=models.URLField(blank=True, help_text='URL to Twitter profile.', null=True),
        ),
        migrations.AlterField(
            model_name='siteidentity',
            name='logo',
            field=models.ImageField(blank=True, help_text='The main logo of the site (e.g., for light backgrounds).', null=True, upload_to='site/'),
        ),
    ]
