# Generated by Django 5.2.3 on 2025-06-16 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Campaign Name')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='Campaign Name')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='Campaign Name')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('subject_en', models.CharField(max_length=255, null=True, verbose_name='Subject')),
                ('subject_de', models.CharField(max_length=255, null=True, verbose_name='Subject')),
                ('subject_fr', models.CharField(max_length=255, null=True, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_de', models.TextField(null=True, verbose_name='Content')),
                ('content_fr', models.TextField(null=True, verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('status_en', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10, null=True)),
                ('status_de', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10, null=True)),
                ('status_fr', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('email_en', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('email_de', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('email_fr', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('first_name_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('first_name_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('last_name_de', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('last_name_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='newsletter.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='newsletter.subscriber')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
